# Generated by Django 5.1 on 2024-08-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reminder_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
